In [1]:
# !pip install gymnasium

import gymnasium as gym
from gymnasium.utils.env_checker import check_env

In [2]:
from pvz_env import GameEnv

env = GameEnv()

Box(0, [  45 2000   45   45 1000], (5,), int32)


In [3]:
env.__class__.__dict__

mappingproxy({'__module__': 'pvz_env',
              'metadata': {'render_modes': ['human'], 'render_fps': 30},
              '__init__': <function pvz_env.GameEnv.__init__(self, grid_rows=9, grid_cols=5, render_mode=None)>,
              'reset': <function pvz_env.GameEnv.reset(self, seed=None, options=None)>,
              'step': <function pvz_env.GameEnv.step(self, action)>,
              'render': <function pvz_env.GameEnv.render(self)>,
              'encode_plants': <function pvz_env.GameEnv.encode_plants(self, plants)>,
              '__doc__': None,
              '__parameters__': ()})

In [4]:
# Here the size of the obs space is (4,)
env.reset()

encode: []
plants :[]
pos: [0 0]
zombies : [0]
[] [5000] [0 0] [0]
obs:  [5000    0    0    0]


(array([5000,    0,    0,    0], dtype=int32), {})

Here is the problem: pos(ition) is a two element array. That's why in the step action you have 5 elements since you are concatenating


In [5]:
env.action_space

Discrete(7)

In [6]:
# This is how they observation space should look like
env.observation_space.sample()
# The output means that there are 4 boxes?

array([  23, 1474,    8,   44,  720], dtype=int32)

In [7]:
# the output type is an array of size 4
# Here the output of the obs after applying the action is (5,)
env.step(action=env.action_space.sample())

reward:  0


(array([5000,    0,    0,    0], dtype=int32), 0, False, False, {})

In [8]:
import numpy as np

In [9]:
np.concatenate(([1], [2], [3], [3, 4]))

array([1, 2, 3, 3, 4])